# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2e94eb54f96d4eb64e080080bc81150ca2753e71dc772bbb9967e1aa210efb738739cdff3a82d1de5b881a45a15d54cf4e5ead47124a7ba20141b16aac9f6a7

test:
  secret_key_base: a00f00ec1d63df063efa28aee390622cf3fa3b98b5bf1789ea716750b863c3ec8058362abb4d474a15d8b5c0674316598e4f66689831843f094b2125ec1f35f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
